### PR TITLE
MANIFEST.in: Include docs, tests, etc

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
Replicating https://github.com/isagalaev/ijson/pull/74 here; with more stuff included.

fwiw, I have been trying to package it at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-ijson

**Comment by rtobar** [comment]
Hi @jayvdb,

I'm not opposed to this addition necessarily, but on the other hand I don't see a clear motivation for including these extra files in the PyPI `sdist` tarballs. Is your packaging effort (is it "official" or a personal one?) failing in any way due to the absence of these files? If you could comment on this it would be great, thanks! :)

**Comment by jayvdb** [comment]
As noted in the commit message, packagers need the tests to validate the package on their environment, which will be constantly changing as dependencies are updated.  Without `tests.py` in the sdist, I need to manually fetch it from GitHub for each release.

Including the changelog allows the packagers to more easily write up what has changed since the last release.

tox.ini helps packagers see how to get the tests running, but that is not critical - they can find it here.

`benchmark.py` is also optional; packagers rarely run any benchmarking tests.

A better question is: why exclude them?
PyPI wheels are what most users will fetch, so size of the sdist is irrelevant.
PyPI sdists are source distributions, so they may as well include all the important 'meta' files from the source that as versioned snapshots, and PyPI versions are more 'real' than GitHub ones, as it is the PyPI version which most users consume.  And who knows, in 20 years maybe GitHub is the next Sourceforge and is a wasteland nobody uses.  PyPI will survive long after GitHub.

**Comment by rtobar** [comment]
Hi @jayvdb I wasn't able previously to find any further information in your commit message or in the PR description for the motivation of the changes, which is why I was asking for some clarifications, thanks a lot for those.

To address your last question, they have been excluded (so far) partly because some of them are fairly new, but also because the need hadn't arise. I would normally pack the bare minimum, which is also what setuptools does by default. In my experience, which might be limited, I've always included the minimum necessary to build and install the package, and this is the first time I am confronted with the necessity to include more files to ease third-party packaging (is this a personal effort, or an official OpenSuSE package?). I had assumed that the source code repositories were always used as the source instead of the per-language package repositories, but it seems I'm wrong in that one?

Also, before posting my previous reply I looked around a bit online to see if there were any guidelines regarding what should or not be included in a source distribution, but I found no clear-cut recommendations. It is clear that at least what is needed to build/install has to be there, but anything else seems to be pretty much at the will of authors (see https://packaging.python.org/guides/using-manifest-in for instance).

Having said all of that, and as I said originally, I'm not opposed to the changes really, so I just merged them.

**Comment by jayvdb** [comment]
I've submitted my package for inclusion into official openSUSE collection.

**Comment by jayvdb** [comment]
https://build.opensuse.org/package/show/devel:languages:python/python-ijson now officially part of openSUSE Tumbleweed.
Should appear on https://repology.org/project/python:ijson/versions in the next batch update.

**Pull request merged**
