### PR TITLE
Added .editorconfig:

### PR DESCRIPTION
**Pull request by KOLANICH**
* python files according to PEP 8
* other files: the same, but tabs instead of spaces
* YAML files: spaces + a tab is 2 space wide

Fixed the .c file to match the config

### CODE REVIEW

**Comment by KOLANICH** [comment]
Probably https://github.com/htmlacademy/editorconfig-cli , but I recomment to stay away of node.js and especially npm as much as possible.

**Comment by rtobar** [comment]
I'm basically thinking on a way to enforce/verify these settings after they are added to the repository, something that could run automatically in TravisCI or other service that could stop anyone from pushing code not following the rules -- otherwise those who user editors not obeying `.editorconfig` will potentially produce incompatible results, and there wouldn't be too much value on adding this to begin with.

I just tried out https://github.com/htmlacademy/editorconfig-cli and it produced a number of false-positives, even after using `-i python-comments -i c-comments`, e.g.:

```
File: ijson/__init__.py
Line: 7 Expected an indentation at 4 instead of at 2. [warning]
Line: 10 Expected an indentation at 4 instead of at 2. [warning]
```

It also produces a lot of positive positives, which would still need to be fixed.

And BTW, thanks for the fixes on the `.c` files already, that looks pretty nice.

**Comment by rtobar** [comment]
@KOLANICH the source code has changed quite a bit since this PR came, but the questions/concerns outlined in my last comment still hold. Could you address those? Otherwise I think I'll have to pass on this one.

**Comment by rtobar** [comment]
Closing after a long time of inactivity. If you want to pursue this in the future please open again, taking note of the comments above.

**Pull request closed without merging**
