### PR TITLE
Arm64 wheels using travis.com

### PR DESCRIPTION
**Pull request by tsahee**
This PR addresses https://github.com/ICRAR/ijson/issues/35, according to the discussions there.

As you already have a travis.com test, all that's needed to support uploading wheels would be to add TWINE_PASSWORD env variable to travis with proper API key from pypi.

Wheels will be built on every push, but only published on tags, (see the test on the "on_success"). I also separated wheel building from tests, so wheels will only be built after all tests pass (this is not a must).

I did not change the github-actions files. You could mix and match which built will be built where. Cibuildwheel seems to support all the wheels you currently use on travis.com.

If there are any questions/comments - I'd be happy fix things as needed.

Thank you!
Tsahi.

### CODE REVIEW

**Comment by tsahee** [comment]
almost forgot - to use the test pypy server I also created the env variable TWINE_REPOSITORY and set it testpypy. To go back to master - just delete the env variable.

**Comment by rtobar** [comment]
@tsahee I'm just pinging to let you know that I'm aware of this PR and will try to find some time this week to test it. I had a quick overlook and it looked fine, but I'd like to take it for a test drive before merging.

**Comment by rtobar** [comment]
I finally got some time to take this for a test ride. It works and it does what it says on the tin, so I'll be merging it in. I will then disable the GitHub Actions (there's no point on keeping both of them) and will make a new `3.1.2.post0` release or similar.

**Comment by rtobar** [comment]
These changes are now contained in the `master` branch. Please note that I cherry-picked your commit instead of merging (see https://github.com/ICRAR/ijson/commit/fcb6190b3d5b576878d52a3ccdfb64e49605e360) -- this is just me trying to keep a linear history and avoid having empty commits. So while this PR will appear as "closed", in reality the work has been fully incorporated.

**Comment by tsahee** [comment]
thank you!

**Pull request closed without merging**
