### PR TITLE
Perf. Improvement for number str_value cast.

### PR DESCRIPTION
**Pull request by SalomonSmeke**
Small improvement I had on my fork way back when! Prevents iterating the str_value thrice, and in some cases returns before completing an iteration.

Made a significant difference in my application, though its been so long that might as well be anecdotal.

### CODE REVIEW

**Comment by rtobar** [comment]
Hi @SalomonSmeke, thanks for the interest and for submitting the patch.

At first glance it looks good, but I gave it a try and I saw performance regressing a bit. Here are three runs of the `benchmark.py` tool against the current master and then against your changes, running the `big_decimal_object` benchmark (i.e., a big JSON document only with numbers) across all my locally available backends:

```shell
$> git co origin/master; python benchmark.py -s 1000000 -b big_decimal_object; git co SalomonSmeke/patch-2; python benchmark.py -s 1000000 -b big_decimal_object
HEAD is now at 13cd7aa Specific python implementations/versions list
#mbytes,method,test_case,backend,time,mb_per_sec
22.676, basic_parse, big_decimal_object, python, 6.007, 3.775
22.676, basic_parse, big_decimal_object, yajl2, 3.483, 6.510
22.676, basic_parse, big_decimal_object, yajl2_cffi, 2.903, 7.812
22.676, basic_parse, big_decimal_object, yajl2_c, 0.489, 46.381
Previous HEAD position was 13cd7aa Specific python implementations/versions list
HEAD is now at ab3a711 Perf. Improvement for number str_value cast.
#mbytes,method,test_case,backend,time,mb_per_sec
22.676, basic_parse, big_decimal_object, python, 6.589, 3.442
22.676, basic_parse, big_decimal_object, yajl2, 4.228, 5.363
22.676, basic_parse, big_decimal_object, yajl2_cffi, 3.489, 6.500
22.676, basic_parse, big_decimal_object, yajl2_c, 0.490, 46.308

$> git co origin/master; python benchmark.py -s 1000000 -b big_decimal_object; git co SalomonSmeke/patch-2; python benchmark.py -s 1000000 -b big_decimal_object
Previous HEAD position was ab3a711 Perf. Improvement for number str_value cast.
HEAD is now at 13cd7aa Specific python implementations/versions list
#mbytes,method,test_case,backend,time,mb_per_sec
22.676, basic_parse, big_decimal_object, python, 6.053, 3.746
22.676, basic_parse, big_decimal_object, yajl2, 3.679, 6.163
22.676, basic_parse, big_decimal_object, yajl2_cffi, 2.975, 7.623
22.676, basic_parse, big_decimal_object, yajl2_c, 0.488, 46.470
Previous HEAD position was 13cd7aa Specific python implementations/versions list
HEAD is now at ab3a711 Perf. Improvement for number str_value cast.
#mbytes,method,test_case,backend,time,mb_per_sec
22.676, basic_parse, big_decimal_object, python, 6.446, 3.518
22.676, basic_parse, big_decimal_object, yajl2, 4.082, 5.556
22.676, basic_parse, big_decimal_object, yajl2_cffi, 3.466, 6.542
22.676, basic_parse, big_decimal_object, yajl2_c, 0.488, 46.488

$> git co origin/master; python benchmark.py -s 1000000 -b big_decimal_object; git co SalomonSmeke/patch-2; python benchmark.py -s 1000000 -b big_decimal_object
Previous HEAD position was ab3a711 Perf. Improvement for number str_value cast.
HEAD is now at 13cd7aa Specific python implementations/versions list
#mbytes,method,test_case,backend,time,mb_per_sec
22.676, basic_parse, big_decimal_object, python, 5.945, 3.814
22.676, basic_parse, big_decimal_object, yajl2, 3.456, 6.561
22.676, basic_parse, big_decimal_object, yajl2_cffi, 2.966, 7.645
22.676, basic_parse, big_decimal_object, yajl2_c, 0.488, 46.452
Previous HEAD position was 13cd7aa Specific python implementations/versions list
HEAD is now at ab3a711 Perf. Improvement for number str_value cast.
#mbytes,method,test_case,backend,time,mb_per_sec
22.676, basic_parse, big_decimal_object, python, 6.463, 3.509
22.676, basic_parse, big_decimal_object, yajl2, 4.067, 5.576
22.676, basic_parse, big_decimal_object, yajl2_cffi, 3.443, 6.587
22.676, basic_parse, big_decimal_object, yajl2_c, 0.487, 46.571
```

With the change the performance of all `python`, `yajl2` and `yajl2_cffi` decreases (`yajl2_c` doesn't use the `number` function). Have you seen something different? This was using python 3.7.

Please let me know your measurements, but unless we see something different I'll have to decline this pull request.

**Comment by rtobar** [comment]
Oh, and just to point out, the C backend does character-by-character checking already: https://github.com/ICRAR/ijson/blob/13cd7aac948ec7f6b916fd0d97da9466729a57ea/ijson/backends/yajl2_c/basic_parse_basecoro.c#L67-L73

**Comment by SalomonSmeke** [comment]
Oh Interesting!

This seems like sufficient evidence to me, id suggest reversing the order of the bench to see if that makes a difference, but I dont think that is likely to yield different results.

Thank you very much for looking into this and taking care of iJson! Looking to switch from our fork to upstream soon.

Ill do some benchmarking of the number function by itself in our production environment (python 3.6.5) to see if I cant get a definitive answer here.

**Comment by rtobar** [comment]
> id suggest reversing the order of the bench to see if that makes a difference

As in looping over the backends in the reverse order? Please feel free to try it out, the benchmark tool allows you to specify which backends to use.

**Comment by SalomonSmeke** [comment]
As in doing my fork and then the regular bench. Yeah ill give it a go later this week if thats ok!

**Comment by rtobar** [comment]
Sure, it would be good to see results in platforms other than mine.

**Comment by rtobar** [comment]
@SalomonSmeke any news on your end regarding benchmarking? Otherwise I'd say let's close this.

**Comment by rtobar** [comment]
It seems performance does not necessarily improves with this patch, so unless we find otherwise in the future, and given that It's been a while since the original reporting came up I'll be closing this now.

**Comment by SalomonSmeke** [comment]
Hey @rtobar im very sorry this dropped off my radar, it seems I messed up my email filters in a _bad_ way, I just noticed this was closed because my PR's dropped by 1 without me merging anything and I thought "that's odd".

Absolutely makes sense to close it. thank you for being so patient and polite.

Cheers.

**Pull request closed without merging**
